/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArquivosRestritosRouteImport } from './routes/arquivos-restritos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as CategoriaCategoryRouteImport } from './routes/categoria.$category'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminNovoRouteImport } from './routes/_authenticated/admin.novo'
import { Route as AuthenticatedAdminEditarIdRouteImport } from './routes/_authenticated/admin.editar.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRestritosRoute = ArquivosRestritosRouteImport.update({
  id: '/arquivos-restritos',
  path: '/arquivos-restritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCategoryRoute = CategoriaCategoryRouteImport.update({
  id: '/categoria/$category',
  path: '/categoria/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNovoRoute = AuthenticatedAdminNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEditarIdRoute =
  AuthenticatedAdminEditarIdRouteImport.update({
    id: '/editar/$id',
    path: '/editar/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivos-restritos': typeof ArquivosRestritosRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$category': typeof CategoriaCategoryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/editar/$id': typeof AuthenticatedAdminEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivos-restritos': typeof ArquivosRestritosRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$category': typeof CategoriaCategoryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki': typeof WikiIndexRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/editar/$id': typeof AuthenticatedAdminEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/arquivos-restritos': typeof ArquivosRestritosRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$category': typeof CategoriaCategoryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
  '/_authenticated/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/editar/$id': typeof AuthenticatedAdminEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivos-restritos'
    | '/auth'
    | '/dashboard'
    | '/linha-do-tempo'
    | '/sitemap.xml'
    | '/admin'
    | '/categoria/$category'
    | '/wiki/$slug'
    | '/wiki/'
    | '/admin/novo'
    | '/admin/usuarios'
    | '/admin/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivos-restritos'
    | '/auth'
    | '/dashboard'
    | '/linha-do-tempo'
    | '/sitemap.xml'
    | '/admin'
    | '/categoria/$category'
    | '/wiki/$slug'
    | '/wiki'
    | '/admin/novo'
    | '/admin/usuarios'
    | '/admin/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/arquivos-restritos'
    | '/auth'
    | '/dashboard'
    | '/linha-do-tempo'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/categoria/$category'
    | '/wiki/$slug'
    | '/wiki/'
    | '/_authenticated/admin/novo'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArquivosRestritosRoute: typeof ArquivosRestritosRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LinhaDoTempoRoute: typeof LinhaDoTempoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriaCategoryRoute: typeof CategoriaCategoryRoute
  WikiSlugRoute: typeof WikiSlugRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos-restritos': {
      id: '/arquivos-restritos'
      path: '/arquivos-restritos'
      fullPath: '/arquivos-restritos'
      preLoaderRoute: typeof ArquivosRestritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$category': {
      id: '/categoria/$category'
      path: '/categoria/$category'
      fullPath: '/categoria/$category'
      preLoaderRoute: typeof CategoriaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/novo': {
      id: '/_authenticated/admin/novo'
      path: '/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AuthenticatedAdminNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/editar/$id': {
      id: '/_authenticated/admin/editar/$id'
      path: '/editar/$id'
      fullPath: '/admin/editar/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditarIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminNovoRoute: typeof AuthenticatedAdminNovoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminEditarIdRoute: typeof AuthenticatedAdminEditarIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminNovoRoute: AuthenticatedAdminNovoRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminEditarIdRoute: AuthenticatedAdminEditarIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArquivosRestritosRoute: ArquivosRestritosRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LinhaDoTempoRoute: LinhaDoTempoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriaCategoryRoute: CategoriaCategoryRoute,
  WikiSlugRoute: WikiSlugRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
